### ISSUE TITLE
[question] which texture unit should be used?

### ISSUE THREAD

**Issue by Gnimuc** [capnramses/antons_opengl_tutorials_book#25]
In example 12, these 4 textures are bound to texture unit GL_TEXTURE1-4 respectively:
https://github.com/capnramses/antons_opengl_tutorials_book/blob/bbc772ac5f254df93457190a1b9ddb6b4e35b316/12_debugging_shaders/main.cpp#L167-L176

but when loading these textures via `load_texture`,  `GL_TEXTURE0` is being reactive again:

https://github.com/capnramses/antons_opengl_tutorials_book/blob/bbc772ac5f254df93457190a1b9ddb6b4e35b316/12_debugging_shaders/main.cpp#L72

so what's the purpose here, the book doesn't tell much about this example?

**Comment by capnramses** [comment]
ah okay. every time you call `glBindTexture()` it binds the texture into the currently active texture unit. it can save some pain later to always call `glActiveTexture( ... )` before any call to `glBindTexture()` so that you know exactly where each texture is being bound in to. i default to always use `GL_TEXTURE0` unless i definitely need more than one texture in a shader. basically it's to avoid "aaah why is my second texture still black?" hair-pulling issues with any multi-texturing. you could do this a different way but i find this the least painful approach so far. hope that answers your question! in summary, no they don't need to load into texture unit 0 - just a hair saver to avoid needing to debug stuff later.

**Comment by Gnimuc** [comment]
That makes sense, thanks for your thorough explanation! Merry Christmas🎄 🎄 🎄
